selftest:
 stage: build
 before_script:
  - eval `ssh-agent`
  - ssh-add ~/gitlab_deploy
 cache:
   paths:
     - parts/
 script:
  - python bootstrap-buildout.py
  - bin/buildout
  - bin/npm install
  - bin/npm install jquery-deparam
  - bin/gulp build --dev --interactive=false
deploy:
 stage: deploy
 script:
  - deploy_theme.sh
 only:
  - master
