selftest:
 stage: build
 cache:
   paths:
     - parts/
 script:
  - sh ./gitlab-ci-selftest.sh
deploy:
 stage: deploy
 cache:
   paths:
     - parts/
 script:
  - sh ./gitlab-ci-deploy.sh
 only:
  - master

pages:
  stage: deploy
  cache:
    paths:
      - build/
  script:
  - sh ./gitlab-ci-pages.sh

  artifacts:
    paths:
    - public

  only:
  - master
