selftest:
 stage: build
 before_script:
  - eval `ssh-agent`
  - ssh-add ~/gitlab_deploy
 cache:
   paths:
     - parts/
 script:
  - sh ./prepare_build_theme.sh
  - bin/gulp build --dev --interactive=false
deploy:
 stage: deploy
 before_script:
  - eval `ssh-agent`
  - ssh-add ~/gitlab_deploy
 cache:
   paths:
     - parts/
 script:
  - sh ./prepare_build_theme.sh
  - bin/gulp build --interactive=false --ver="`git rev-parse --short HEAD`"
  - sh ./deploy_theme.sh
 only:
  - master

pages:
  before_script:
  - eval `ssh-agent`
  - ssh-add ~/gitlab_deploy
  stage: deploy
  cache:
    paths:
      - build/
  script:
  - sh ./prepare_build_theme.sh
  - bin/gulp build --interactive=false --ver="`git rev-parse --short HEAD`"
  - sh ./deploy_theme.sh
  - bin/gulp relative-paths
  - 'curl -o milestones.json --header "PRIVATE-TOKEN: oatBqMZzaiuxaa5sf7az" https://gitlab.fhnw.ch/api/v4/projects/25/milestones'
  - cp milestones.json build/
  - mv build public

  artifacts:
    paths:
    - public

  only:
  - release-notes2
