selftest:
 stage: build
 cache:
   paths:
     - parts/
 script:
  - sh ./prepare_build_theme.sh
  - bin/node --version
  - bin/nodejs --version
  - bin/gulp --version
  - bin/gulp build --dev --interactive=false
deploy:
 stage: deploy
 cache:
   paths:
     - parts/
 script:
  - sh ./prepare_build_theme.sh
  - bin/gulp build --interactive=false --ver="`git rev-parse --short HEAD`"
  - DO_COMMIT=yes sh ./deploy_theme.sh
 only:
  - master

pages:
  stage: deploy
  cache:
    paths:
      - build/
  script:
  - sh ./prepare_build_theme.sh
  - bin/gulp build --interactive=false --ver="`git rev-parse --short HEAD`"
  - sh ./deploy_theme.sh
  - bin/gulp relative-paths
  - 'curl -o milestones.json --header "PRIVATE-TOKEN: oatBqMZzaiuxaa5sf7az" https://gitlab.fhnw.ch/api/v4/projects/25/milestones'
  - cp milestones.json build/
  - 'curl -o commits.json --header "PRIVATE-TOKEN: oatBqMZzaiuxaa5sf7az" https://gitlab.fhnw.ch/api/v4/projects/257/repository/commits'
  - cp commits.json build/
  - mv build public

  artifacts:
    paths:
    - public

  only:
  - master
